# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lg2xg3kucIsRe6Icjr5IQPAmG9O_7kvp
"""

import time
print("+----------------------------------------+")
print("SELAMAT DATANG DI PERHITUNGAN MUNDUR !!!")
print("+........................................+")
urname = input("Isikan Nama Anda ")
print(f"Lakukan Perhitungan Bersamaku {urname}! ")
print("........................................")

time.sleep(1)
print("times up")

time.sleep(3)
print("times up")

my_time = int(input("jeda waktu yang diperlukan untuk keluar output dalam hitungan detik "))
for x in range(0, my_time):
   time.sleep(1)

print("end")

my_time = int(input("masukan dalam hitungan detik : "))

for x in range(my_time, 0, -1):
   seconds = x % 60
   print(f"00:00: {seconds:02}")
   time.sleep(1)

print("waktu habis bang !!!")

my_time = int(input("masukan menit dalam hitungan detik : "))
for x in range(my_time, 0, -1):
   seconds = x % 60
   minutes =int(x / 60) % 60
   print(f"00:{minutes:02}:{seconds:02} ")
   time.sleep(1)

print("waktu habis bang")

my_time = int(input("masukan jam dalam hitungan detik : "))
for x in range(my_time, 0, -1):
   seconds = x % 60
   minutes =int(x / 60) % 60
   hours =int(x / 3600 )
   print(f"{hours:02}:{minutes:02}:{seconds:02} ")
   time.sleep(1)

print("waktu habis bang")

"""NAUVAL IHSANI AZIS / 21083010121
COUNTDOWN TIMER
"""

